name: "Global Workflows Support"
description: >
  This action introduces support for global workflows. 
  Global workflows are the one you update in just one repo and they are automatically updated in other repositories."
inputs:
  github_token:
    description: >
      Token to use GitHub API. 
      It cannot be the default GitHub Actions token GITHUB_TOKEN. GitHub Action token's permissions are limited to the repository that contains your workflows.
      Provide token of the user that has rights to push to the repos that this action is suppose to update. 
    required: true
  committer_username:
    description: >
      The username (not display name) of the committer that will be used in the commit of changes in the workflow file in specific repository.
      Must match the username of the github_token owner.
      In the format `github-actions`.
    default: github-actions
    required: false
  committer_email:
    description: >
      The email of the committer that will be used in the commit of changes in the workflow file in specific repository.
      Must match the email of the github_token owner
      In the format `Display Name`.
    default: noreply@github.com
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "link"
  color: "blue"
